[package]
name = "collaborative-chat"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
slack-flows = "0.2"
openai-flows = "0.2"
store-flows = "0.2"
serde_json = "1.0"
dotenv = "0.15.0"
