[package]
name = "collaborative-chat"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
slack-flows = "0.3"
openai-flows = "0.7"
dotenv = "0.15.0"
tokio_wasi = { version = "1.25.0", features = ["rt", "macros"] }
